export const prompts = [
  "What's something that challenged you today, and how did you respond to it?",
  "Describe a moment today that made you smile.",
  "What did you learn about yourself recently?",
  "Write about a goal you're working towards and your progress.",
  "Reflect on a recent decision and its outcome.",
    "What made you smile today? Describe the moment in detail.",
    "Write about one challenge you faced today and how you handled it.",
    "What are three things you're grateful for right now, and why?",
    "Describe your current mood as a weather pattern. What caused this 'weather'?",
    "What's one thing you learned today—about yourself, others, or the world?",
    "If you could redo one moment from today, what would it be and how would you change it?",
    "What's something you're looking forward to tomorrow or in the near future?",
    "Write a letter to your future self about where you are right now in life.",
    "What's one small win you experienced today that deserves celebration?",
    "How did you care for your physical and mental well-being today?",
    "What conversation had the biggest impact on you today? Why?",
    "Describe a moment of beauty or wonder you experienced or witnessed today.",
    "What made you feel challenged, uncomfortable, or stressed today? What might this teach you?",
    "If today were a chapter in the book of your life, what would its title be?",
    "What boundaries did you maintain or need to set today?",
    "Write about someone who positively influenced your day, even in a small way.",
    "What did you do today that aligned with your core values?",
    "What's something you need to forgive yourself for today?"
];
